version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  test-sub-project:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - cd sub-project
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test