version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  sub-project-test:
    executor:
      name: node/default
      tag: '14.16'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd sub-project && npm install
      - run: cd sub-project && npm run test

workflows:
  sub-project:
    jobs:
      - sub-project-test