name: Build
on:
  push:
    branches:
      - main
jobs:
  manual-approval:
    environment:
      name: Production
      url: bramvanderputten.com
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.16
      - run: |
          cd sub-project
          npm install
          npm run build