name: Test sub-project
on:
- push
jobs:
  test_sub_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.16
    - run: |
        cd sub-project
        npm install
        npm test