name: Test sub-project
on:
  push:
    branches:
      - main
jobs:
  test_sub_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - run: |
        cd sub-project
        npm install
        npm test
  deploy:
    runs-on: ubuntu-latest
    needs: test_sub_project
    environment:
      name: Production
      url: bramvanderputten.com
    steps:
      - uses: actions/checkout@v2